### ISSUE TITLE
[Bug] supabaseUrl is required - support form not working!

### ISSUE THREAD

**Issue by miraclebg** [podkrepi-bg/frontend#320]
After the latest deployment it is not possible to submit the support / contact form due to the following error reported by the frontend container:

```
Error: supabaseUrl is required.
    at new SupabaseClient (/app/node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js:46:19)
    at createClient (/app/node_modules/@supabase/supabase-js/dist/main/index.js:25:12)
    at Object.6895 (/app/.next/server/pages/api/support-request.js:41:62)
    at __webpack_require__ (/app/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/app/.next/server/pages/api/support-request.js:109:52)
    at /app/.next/server/pages/api/support-request.js:110:52
    at Object.<anonymous> (/app/.next/server/pages/api/support-request.js:113:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
```

For whatever reason the script is not reading the two envrionment variables properly:

- NEXT_PUBLIC_SUPABASE_URL
- NEXT_PUBLIC_SUPABASE_KEY

I've tried to add these two next.config.js but it still does not work:

```
env: {
    APP_ENV: process.env.APP_ENV,
    SENTRY_DSN: process.env.SENTRY_DSN,
    DEPLOY_TAG: process.env.DEPLOY_TAG,
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_KEY: process.env.NEXT_PUBLIC_SUPABASE_KEY,
  },
```

The environment variables have properly been defined in the github actions deployment files and in the docker compose files.

**Comment by kachar** [comment]
Just rolled back to the initial solution using own db storage via the support request endpoint of the go api client.

No supabase usage anymore, it has served it's purpose in the pre-release pressure moment.
